---
apiVersion: v2
name: irs
description: A Helm chart for Kubernetes

type: application
version: 0.0.1
appVersion: "1.0.0"

dependencies:

  - name: omejdn-service
    alias: omejdn-service
    version: 0.0.1
    repository: "file://subcharts/omejdn-service"
    condition: install.omejdn
