@hostname = localhost
@port = 4567
@host = {{hostname}}:{{port}}
@token = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhY2MiLCJzdWIiOiJhY2MiLCJleHAiOjE2NzY0NTUzNTcsIm5iZiI6MTY3NjQ1MTc1NywiaWF0IjoxNjc2NDUxNzU3LCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQ1NjcifQ.GRrmmG41D2lwvOo-VUDGmjKvp5Viay7fBLjOkFUPdkU5pbDYvzMWtvsbvIKdKbM7xrjGtDe1sHyOy2KGbPb9o1VjBIeP3c8VPeuV17bTQs90B5tbiEJwhI8gYrLLR2ezld_4NtTbhfOkCDRos86JSE16qf4MTGl8jRPQlMv5doIBlswARi90FUvwuQjS0A5O3T3JzJpcrfFWrHCPPIHSI282DkaUdBMy2HUQ52LaN6mf9uWbwlBxU515z-7i1PwRgrirfZQMeLIYa3QXhGEbcrP4rwP8W7vB5Z5WY5S0ZnjFvCt4V5CyGVXMZnkn3sOmno6pa6-3w8Omb1xopWKZAw
@grantType = client_credentials
@client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer
@scope = openid profile omejdn:admin idsc:IDS_CONNECTOR_ATTRIBUTES_ALL

### Get JWKS
GET http://{{host}}/jwks.json HTTP/1.1
Content-Type: application/json

### Get OpenId Configuration
GET http://{{host}}/.well-known/openid-configuration HTTP/1.1
Content-Type: application/json

### Get Token
POST http://{{host}}/token HTTP/1.0
Content-Type: application/x-www-form-urlencoded

grant_type={{grantType}}
&client_assertion_type={{client_assertion_type}}
&client_assertion={{token}}
&scope={{scope}}
