@hostname = localhost
@port = 4567
@host = {{hostname}}:{{port}}
@token = eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJhY2MiLCJzdWIiOiJhY2MiLCJleHAiOjE2NzY0NDk3MTEsIm5iZiI6MTY3NjQ0NjExMSwiaWF0IjoxNjc2NDQ2MTExLCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjQ1NjcifQ.fWD-jZawBhSPjItg81wZKUzWxfRgwE8sT7LFrzXN3whxxAH01fiiK717eFwsfGNiKEXbIVtM7kQYioXLWAcX_il8yHnRNXUbyAlZqb6vKR0WosU7kuHkaYU-WxW5Zj1Fe-Sufo-uctjVsDIYi6inw13J4OkaFMW0dSQCx-lY4yA8aS_K2l5qkXbW_WGNP1rVsmftetCkRl0r3pU0uiXc608b_WztibR6Oro0XOMxWIBFIrj34XWHN7JsCScz33og2kB-OqfLSKs2OUXKpu7MGE21gHpxVU5eMGo2t_wGp175VTeNvwvKgbLK7Rp6wNXvXISoIgznbtHOTxSYTpbu6Q
@grantType = client_credentials
@client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer
@scope = openid profile omejdn:admin idsc:IDS_CONNECTOR_ATTRIBUTES_ALL

### Get JWKS
GET http://{{host}}/jwks.json HTTP/1.1
Content-Type: application/json

### Get OpenId Configuration
GET http://{{host}}/.well-known/openid-configuration HTTP/1.1
Content-Type: application/json

### Get Token
POST http://{{host}}/token HTTP/1.0
Content-Type: application/x-www-form-urlencoded

grant_type={{grantType}}
&client_assertion_type={{client_assertion_type}}
&client_assertion={{token}}
&scope={{scope}}
